# Generated by Django 2.1.3 on 2019-06-06 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Desktops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=80, verbose_name='设备编码')),
                ('name', models.CharField(max_length=80, verbose_name='设备名称')),
                ('brand', models.CharField(max_length=80, verbose_name='品牌')),
                ('number', models.CharField(max_length=80, verbose_name='数量')),
                ('type', models.CharField(max_length=80, verbose_name='型号')),
                ('department', models.CharField(max_length=80, verbose_name='部门')),
                ('user', models.CharField(max_length=80, verbose_name='使用人')),
                ('statue', models.CharField(max_length=80, verbose_name='状态')),
                ('location', models.CharField(max_length=80, verbose_name='所在位置')),
                ('delivery_time', models.CharField(max_length=80, verbose_name='出厂时间')),
                ('remark', models.CharField(max_length=80, verbose_name='备注')),
            ],
        ),
    ]
